# Generated by Django 5.1.3 on 2024-11-12 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disponibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('dias', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Donacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_donacion', models.CharField(choices=[('ropa', 'Ropa'), ('alimentos', 'Alimentos'), ('dinero', 'Dinero')], max_length=50)),
                ('detalles', models.TextField()),
                ('cantidad', models.IntegerField()),
                ('fecha_disponible', models.DateField()),
                ('hora_disponible', models.TimeField()),
                ('confirmacion_enviada', models.BooleanField(default=False)),
                ('foto_comprobante', models.BinaryField(blank=True, null=True)),
                ('correo', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Informante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion', models.TextField()),
                ('evidencia', models.BinaryField(blank=True, null=True)),
                ('solicitud_donacion', models.TextField()),
                ('fecha', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Voluntario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('tipo_voluntario', models.CharField(choices=[('campo', 'Campo'), ('acompañador', 'Acompañador'), ('recolector', 'Recolector')], max_length=50)),
                ('disponibilidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.disponibilidad')),
            ],
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_usuario', models.CharField(choices=[('Voluntario', 'Voluntario'), ('Donador', 'Donador'), ('Informante', 'Informante')], max_length=50)),
                ('usuario_id', models.IntegerField()),
                ('detalles', models.TextField()),
                ('fecha_reporte', models.DateField(auto_now_add=True)),
                ('donacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.donacion')),
                ('informante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.informante')),
                ('voluntario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.voluntario')),
            ],
        ),
    ]
